### ISSUE TITLE
Replace Landing Page

### ISSUE THREAD

**Issue by trechriron** [near/wallet-experience#11]
### Description

- Section explaining that NEAR wallet is sunset. Point to [blog](https://medium.com/nearprotocol/near-opens-the-door-to-more-wallets-255eee58eb97) for info.
- Section like Transfer Wizard banner but simpler. Link to [docs](https://wallet.near.org/transfer-wizard). Link to TW. – **only show if user is still logged in to NEAR wallet**.
- Section about supported import-aware wallets from /[transfer-wizard](https://wallet.near.org/transfer-wizard) docs.
- Section (link) about where to buy or exchange NEAR (top up /buy page).
- **Warning: do not make any changes that could impact the wallet.near.org domain.**

**Routes that should be disabled with redirect to “/”;**

- /batch-import
- /batch-ledger-export
- /explore
- /privacy
- /profile/:accountId
- /profile/:accountId?
- /setup-ledger-success
- /terms

**Routes that should be preserved AS IS;**

- Keep the “/” route for the new landing page.
- /disable-two-factor
- /transfer-wizard

### UX Designs – [Figma Link 🔗 ](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/Post-Transition-Landing-Page?type=design&node-id=1-2&mode=design)

![Image subject to change, check Figma file for latest designs and discussion](https://github.com/near/wallet-experience/assets/103140483/50088c4b-1ede-4598-b3fe-1b9ab895425c)
_Image subject to change, check Figma file for latest designs and discussion_

**Comment by trechriron** [comment]
@hcho112 Can you provide the current wallet list from the Transfer Wizard wallet-selector implementation? The order is important for the static page. Thanks!

**Comment by trechriron** [comment]
Here is the order of the wallets from Transfer-Wizard wallet-selector implementation;

- MyNearWallet,
- Meteor Wallet,
- Sender,
- Here Wallet,
- Nightly,
- Welldone Wallet,

**Comment by hcho112** [comment]
This task has been completed and deployed on prod so closing the ticket
