### ISSUE TITLE
Disabled Routes - Static Error Page

### ISSUE THREAD

**Issue by trechriron** [near/wallet-experience#12]
### Description

- A new static “error” page will display for disabled routes.
- Message: “This functionality of NEAR Wallet is not available anymore <Learn more (link to the deprecation blog post)>. Please use the Transfer Wizard to pick a new wallet (link)”.
- Technical → Add Rudderstack tracking on login and sign pages to track referrers and traffic ([requirements](https://docs.google.com/document/d/1OHVx2HfveIejrT_8CMNu1UkJW_B1cS1bl5M8aZkWiV4/edit#heading=h.e9gdjeo06y38)).

**Disabled Routes;**

-  path={'/create-from/:fundingAccountId'}
- /authorized-apps
- /auto-import-secret-key
- /auto-import-seed-phrase
- /buy (be sure to not remove the code for this page)
- /cli-login-success
- /create
- /create-implicit-account
- /create/:fundingContract/:fundingKey
- /enable-two-factor
- /full-access-keys
- /fund-create-account/:accountId/:implicitAccountId/:recoveryMethod
- /fund-with-existing-account
- /initial-deposit
- /linkdrop/:fundingContract/:fundingKey
- /login
- /nft-detail/:contractId/:tokenId
- /profile
- /receive-money
- /recover-account
- /recover-seed-phrase/:accountId?/:seedPhrase?
- /recover-with-link/:accountId/:seedPhrase
- /send-money/:accountId?
- /set-recovery-implicit-account
- /set-recovery/:accountId/:fundingContract?/:fundingKey?
- /setup-ledger-new-account
- /setup-ledger/:accountId
- /setup-passphrase-new-account
- /setup-seed-phrase/:accountId/:step
- /sign
- /sign-in-ledger
- /staking
- /swap
- /verify-account

### UX Designs – [Figma Link 🔗 ](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/Post-Transition-Landing-Page?type=design&node-id=150%3A13320&mode=design&t=m3t34Bgm04VPYDg9-1)
![function unavailable](https://github.com/near/wallet-experience/assets/103140483/13b82e0d-e281-4c31-a60c-0188aac3ecfd)
_Image subject to change, check Figma file for latest designs and discussion_

**Comment by trechriron** [comment]
@nall-near should this be a toast or message at the top the same landing page?

**Comment by nall-near** [comment]
Added [design](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/Post-Transition-Landing-Page?type=design&node-id=150%3A13320&mode=design&t=m3t34Bgm04VPYDg9-1) for error messaging when function is unavailable.

**Comment by hcho112** [comment]
This task has been completed, closing
