### ISSUE TITLE
Routes / Pages Not Changing

### ISSUE THREAD

**Issue by trechriron** [near/wallet-experience#13]
### Description

**Route / Page 3 - wallet.near.org/transfer-wizard**
This wizard and flow should remain the same.

**Route / Page 4 - wallet.near.org/disable-two-factor**
This route should be preserved in the event a customer has not disabled and is having a hardship disabling two-factor authentication. This drives a command line script using the customer’s FAK to quickly disable 2FA.

**Comment by hcho112** [comment]
This task has been completed, closing
