### ISSUE TITLE
Tracking & Analytics

### ISSUE THREAD

**Issue by trechriron** [near/wallet-experience#14]
### Description

Disabled routes should direct the user to a static page with the attempted route as a URL param (e.g., `https://wallet.near.org/sunset?route=%2Flogin)`.

We should also use frontend tracking (via Rudderstack or similar) to log visits to the sunset page, with the following data points:

- "attempted_route": route that originated the error message (eg, /login, /signup)
- "http-referer": HTTP referer that originated the visit to the error page (eg, https://www.ref.finance/)
- "timestamp": timestamp of the visit
- "User": standard Rudderstack user object (anonymized, for aggregation) to be able to track locale, browser, etc.

In addition to logging visits to the page, the following user actions should also be logged:

- Clicks: once the user clicks any of the links or CTAs, including a descriptive name of the element that was clicked.

**Comment by s-n-park** [comment]
Heads up that there is no Rudderstack tracking setup on subdomains currently:

This is the related issue that @charleslavon setup for tracking on Docs. 
https://github.com/near/near-discovery/issues/930

Edit: I forgot that wallet apparently DOES have tracking so feel free to ignore me :)

**Comment by hcho112** [comment]
This change has been completed and deployed to prod. Also confirmed that we see analytics data coming is so will close this ticket
